server:
  port: 8085

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    # url: jdbc:h2:mem:redream
    # driver-class-name: org.h2.Driver
    # username: sa
    # password: password
    # hikari:
    #   max-lifetime: 100000
    #   connection-timeout: 100000
    #   validation-timeout: 100000
    #   maximum-pool-size: 20
    url: jdbc:postgresql://localhost:5432/redream
    username: sa
    password: changeme
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 100000
      connection-timeout: 100000
      validation-timeout: 100000
      maximum-pool-size: 20
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-server:5432/redream